export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REFRESH = 'REFRESH';
export const CHANGE_CREDENTIALS_STARTED = 'CHANGE_CREDENTIALS';
export const CHANGE_CREDENTIALS_SUCCESS = 'CHANGE_CREDENTIALS_SUCCESS';
export const CHANGE_CREDENTIALS_FAILURE = 'CHANGE_CREDENTIALS_FAILURE';