// General
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Chat reducer
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_STARTED = 'ADD_MESSAGE_STARTED';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
export const REFRESH = 'REFRESH';
export const REFRESH_STARTED = 'REFRESH_STARTED';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAILURE = 'REFRESH_FAILURE';

// Settings reducer
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const CHANGE_CREDENTIALS = 'CHANGE_CREDENTIALS';
export const CHANGE_CREDENTIALS_STARTED = 'CHANGE_CREDENTIALS_STARTED';
export const CHANGE_CREDENTIALS_SUCCESS = 'CHANGE_CREDENTIALS_SUCCESS';
export const CHANGE_CREDENTIALS_FAILURE = 'CHANGE_CREDENTIALS_FAILURE';